os:
  - linux

language: java

addons:
  apt:
    packages:
    - cmake
    - time

before_install:
  - echo "Before Install"
install:
  - sudo wget https://mirror.openshift.com/pub/openshift-v3/clients/3.11.16/linux/oc.tar.gz
  - sudo tar -xvf oc.tar.gz -C /usr/bin/
before_script:
  - echo "Before Script"
script:
  - oc version

notifications:
  slack: deepan10:nTGqbkpHVVQ159ViRSnpQIjv
  on_start: change