os:
  - linux

language: java

addons:
  apt:
    packages:
    - cmake
    - time

before_install:
  - echo "Before Install"
install:
  - echo "Install"
before_script:
  - echo "Before Script"
script:
  - echo "Script"

notifications:
  slack: deepan10:nTGqbkpHVVQ159ViRSnpQIjv
  on_start: change